version: '3'
services:
  solr5:
    image: solr:5
    ports:
      - "8984:8983"
    entrypoint:
      - bash
      - "-c"
      - "precreate-core testcore; precreate-core organizations; exec solr -f"
