version: '3'
services:
  solr8:
    image: solr:8
    ports:
      - "8983:8983"
    entrypoint:
      - bash
      - "-c"
      - "precreate-core testcore; precreate-core organizations; exec solr -f"
