---

name: Solr Legacy (5)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    name: Solr Legacy

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 1

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Start Solr
        run: npm run solr:legacy:start

      - name: Run npm install
        run: npm install

      - name: Run Tests
        run: npm run test:legacy
        env:
          CI: true

      - name: Stop Solr
        run: npm run solr:legacy:stop
